--- Collect pokemon information
---
CREATE TABLE IF NOT EXISTS dex (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    POKEID INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    IMGURL TEXT NOT NULL,
    TYPE1 TEXT NOT NULL,
    TYPE2 TEXT,
    HP INTEGER NOT NULL,
    ATK INTEGER NOT NULL,
    DEF INTEGER NOT NULL,
    SPATK INTEGER NOT NULL,
    SPDEF INTEGER NOT NULL,
    SPEED INTEGER NOT NULL
);